#!/bin/bash

set -x

#curl 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | grep ipv4 | grep CN | awk -F\| '{ printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > /chnroute.txt

pid=0

# SIGTERM -handler
term_handler() {
  if [ $pid -ne 0 ]; then
    kill -SIGTERM "$pid";
    #create_ap --stop wlan0
    wait "$pid";
  fi
  exit 143; # 128 + 15 -- SIGTERM
  #exit 0;
}

# setup handlers
# on callback, kill the last background process, which is `tail -f /dev/null` and execute the specified handler
trap 'kill ${!}; term_handler' SIGTERM

ss-redir -u -s $SS_SERVER_IP -p $SS_SERVER_PORT -l $SS_LOCAL_PORT -k $SS_PASSWD -m $SS_METHOD -b 0.0.0.0 -f /var/run/shadowsocks.pid

# run application
create_ap $AP_WIFI_IFACE $AP_INTERNET_IFACE $AP_SSID $AP_PASSPHRASE &
pid="$!"

# wait forever
while true
do
  tail -f /dev/null & wait ${!}
done

